[alias]

[tools]
bun = "latest"
deno = "latest"
go = "latest"
node = "latest"
"ubi:adwinying/php" = "latest"
rust = "latest"
pnpm = "latest"
"ubi:composer/composer" = "latest"

[settings]
experimental = true

[env]
_.file = '.env'
_.path = [
    "{{config_root}}/node_modules/.bin",
    "{{config_root}}/vendor/bin",
]
